# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b6ff6e27eb95cfe54f2900becb86352f3962288464e15a92ff32e8fca5cd716be8ea56257d2b3f38ca35484c8388b71cb7652d0b37dced65f2aecaaa49833f1

test:
  secret_key_base: 7d778a1ea13a777ae9b52f61e1c38883ccb01915b713e6c4fd81ab2e7865ef803300c89cbe1ebf2ab59b97e8c16734a8e660fbcf0ceac02261115b9801163824

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
